Quickinstall link: https://theforeman.org/manuals/3.2/quickstart_guide.html
Manual link: https://theforeman.org/manuals/3.2/index.html

----
[root@katello ~]# sudo foreman-installer -l
2021-07-05 22:47:32 [NOTICE] [root] Loading installer configuration. This will take some time.
2021-07-05 22:47:35 [NOTICE] [root] Running installer with log based terminal output at level NOTICE.
2021-07-05 22:47:35 [NOTICE] [root] Use -l to set the terminal output log level to ERROR, WARN, NOTICE, INFO, or DEBUG. See --full-help for definitions.
2021-07-05 22:48:03 [NOTICE] [configure] Starting system configuration.
2021-07-05 22:49:28 [NOTICE] [configure] 250 configuration steps out of 1338 steps complete.
2021-07-05 22:50:12 [NOTICE] [configure] 500 configuration steps out of 1340 steps complete.
2021-07-05 22:50:27 [NOTICE] [configure] 750 configuration steps out of 1352 steps complete.
2021-07-05 22:52:30 [NOTICE] [configure] 1000 configuration steps out of 1366 steps complete.
2021-07-05 22:53:19 [NOTICE] [configure] 1250 configuration steps out of 1366 steps complete.
2021-07-05 22:53:26 [NOTICE] [configure] System configuration has finished.
Executing: foreman-rake upgrade:run
`/usr/share/foreman` is not writable.
Bundler will use `/tmp/bundler20210705-22083-1535yn622083' as your home directory temporarily.
  Success!
  * Foreman is running at https://katello.luc.ca
      Initial credentials are admin / U9L9C7dWQqPLGRLr
  * Foreman Proxy is running at https://katello.luc.ca:8443

  The full log is at /var/log/foreman-installer/foreman.log

----

[source,bash]
----
   18  sudo yum -y install https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
   19  sudo dnf module reset ruby
   20  sudo dnf module enable ruby:2.7
   21  sudo yum -y install https://yum.theforeman.org/releases/3.2/el8/x86_64/foreman-release.rpm
   22  sudo yum -y install foreman-installer
   23  sudo foreman-installer
   24  sudo firewall-cmd --add-port={22,53,80,443,3000,8140,3306,5432,8443,5910-5930}/tcp --permanent
   25  sudo firewall-cmd --add-port=67-69/udp --permanent
   26  sudo firewall-cmd --reload
----

Katello: https://docs.theforeman.org/3.0/Installing_Server_on_Red_Hat/index-katello.html

yum install foreman-installer-katello
foreman-installer \
 –puppet-server=false \
 –foreman-proxy-puppet=false \
 –foreman-proxy-puppetca=false
foreman-installer –scenario katello –help

foreman-installer –scenario katello \
 –foreman-initial-organization "Lab" \
 –foreman-initial-location "Laptop" \
 –foreman-initial-admin-username "admin" \
 –foreman-initial-admin-password "100395" \
 –puppet-server=false \
 –foreman-proxy-puppet=false \
 –foreman-proxy-puppetca=false

* 

Centos 8 - Katello 4.4

[source,bash]
----
   14  dnf clean all
   15  dnf localinstall https://yum.theforeman.org/releases/3.2/el8/x86_64/foreman-release.rpm
   16  dnf localinstall https://yum.theforeman.org/katello/4.4/katello/el8/x86_64/katello-repos-latest.rpm
   17  dnf install centos-release-ansible-29
   18  dnf localinstall https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
   19  dnf module reset ruby
   20  dnf module enable ruby:2.7
   21  dnf config-manager --set-enabled powertools
   22  dnf module enable postgresql:12
   23  dnf update
   24  dnf install foreman-installer-katello
   25  foreman-installer --scenario katello   --foreman-initial-organization "Lab"   --foreman-initial-location "Laptop"   --foreman-initial-admin-username "admin"   --foreman-initial-admin-password "100395"   --puppet-server=false   --foreman-proxy-puppet=false   --foreman-proxy-puppetca=false
   26  firewall-cmd --add-port={22,53,80,443,3000,8140,3306,5432,8443,5910-5930}/tcp --permanent
   27  firewall-cmd --add-port=67-69/udp --permanent
   28  firewall-cmd --reload
   29  tail -n 1 /etc/hosts
192.168.100.239 foreman.internal-lab.net
----

* 

Libvirt tools

[source,bash]
----
   34  yum install foreman-libvirt
   35  systemctl status foreman
   36  systemctl restart foreman
----

2022-05-16 22:43:09 [NOTICE] [configure] System configuration has finished.

= Executing: foreman-rake upgrade:run

= Upgrade Step 1/8: katello:correct_repositories. This may take a long while.

Upgrade Step 2/8: katello:clean_backend_objects. This may take a long while.
0 orphaned consumer id(s) found in candlepin.

= Candlepin orphaned consumers: []

Upgrade Step 3/8: katello:upgrades:4.0:remove_ostree_puppet_content. =============================================
Upgrade Step 4/8: katello:upgrades:4.1:sync_noarch_content. =============================================
Upgrade Step 5/8: katello:upgrades:4.1:fix_invalid_pools. I, [2022-05-16T22:43:18.946728 #30188] INFO – : Corrected 0 invalid pools

= I, [2022-05-16T22:43:18.946760 #30188] INFO – : Removed 0 orphaned pools

Upgrade Step 6/8: katello:upgrades:4.1:reupdate_content_import_export_perms. =============================================
Upgrade Step 7/8: katello:upgrades:4.2:remove_checksum_values. =============================================
Upgrade Step 8/8: katello:upgrades:4.4:publish_import_cvvs. Success!
 * Foreman is running at https://foreman.internal-lab.net
 Initial credentials are admin / 100395
 * To install an additional Foreman proxy on separate machine continue by running:

----
  foreman-proxy-certs-generate --foreman-proxy-fqdn "$FOREMAN_PROXY" --certs-tar "/root/$FOREMAN_PROXY-certs.tar"
----

* Foreman Proxy is running at https://foreman.internal-lab.net:9090

The full log is at /var/log/foreman-installer/katello.log

----

* Subscription manager: https://computingforgeeks.com/sync-centos-8-repositories-on-satellite-katello-foreman/

----

39 hammer organization list
 40 hammer product create –organization-id 1 –name "CentOS 8 Linux for x86_64" –description "Repositories to use with CentOS 8 Linux"
 45 hammer product list –organization-id 1
 46 mkdir /etc/pki/rpm-gpg/import/
 47 cd /etc/pki/rpm-gpg/import/
 48 wget https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official
 62 hammer content-credentials create –content-type gpg_key –organization-id 1 –path RPM-GPG-KEY-CentOS-Official –name "RPM-GPG-KEY-CentOS-8"
hammer content-credentials list –organization-id 1
hammer repository create –organization-id 1 –product "CentOS 8 Linux for x86_64" –name "CentOS 8 Base RPMS" –label "CentOS_8_Base_RPMS" –content-type "yum" –download-policy "on_demand" –gpg-key-id 1 –url "http://centos.mirror.liquidtelecom.com/8/BaseOS/x86_64/os/" –mirror-on-sync "no"
hammer repository list –organization-id 1
hammer repository delete –product-id 1 –organization-id 1
hammer repository create –organization-id 1 –product "CentOS 8 Linux for x86_64" –name "CentOS 8 Base RPMS" –label "CentOS_8_Base_RPMS" –content-type "yum" –download-policy "on_demand" –gpg-key-id 1 –url "http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/" –mirror-on-sync "no"

117 hammer repository create –organization-id 1 –product "CentOS 8 Linux for x86_64" –name "CentOS 8 AppStream RPMS" –label "CentOS_8_AppStream_RPMS" –content-type "yum" –download-policy "on_demand" –gpg-key-id 1 –url "http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/" –mirror-on-sync "no"
 118 hammer repository create –organization-id 1 –product "CentOS 8 Linux for x86_64" –name "CentOS 8 extras RPMS" –label "CentOS_8_extras_RPMS" –content-type "yum" –download-policy "on_demand" –gpg-key-id 1 –url "http://mirror.centos.org/centos/8-stream/extras/x86_64/os/" –mirror-on-sync "no"
 119 hammer repository create –organization-id 1 –product "CentOS 8 Linux for x86_64" –name "CentOS 8 centosplus RPMS" –label "CentOS_8_centosplus_RPMS" –content-type "yum" –download-policy "on_demand" –gpg-key-id 1 –url "http://mirror.centos.org/centos/8-stream/centosplus/x86_64/os/" –mirror-on-sync "no"
 120 hammer repository list –organization-id 1 –product "CentOS 8 Linux for x86_64"
 121 hammer repository create –organization-id 1 –product "CentOS 8 Linux for x86_64" –name "CentOS 8 PowerTools RPMS" –label "CentOS_8_PowerTools_RPMS" –content-type "yum" –download-policy "on_demand" –gpg-key-id 1 –url "http://mirror.centos.org/centos/8-stream/PowerTools/x86_64/os/" –mirror-on-sync "no"
 122 hammer repository list –organization-id 1 –product "CentOS 8 Linux for x86_64"
 123 hammer repository synchronize –async –organization-id 1 –product "CentOS 8 Linux for x86_64" –id 3;
 124 hammer repository synchronize –async –organization-id 1 –product "CentOS 8 Linux for x86_64" –id 4;
 125 hammer repository synchronize –async –organization-id 1 –product "CentOS 8 Linux for x86_64" –id 5;
 126 hammer repository synchronize –async –organization-id 1 –product "CentOS 8 Linux for x86_64" –id 6;
 127 watch 'df -h /var/lib/pulp'
 128 df -h
 129 watch 'df -h /var/lib/pulp'
 130 hammer content-view create –organization-id 1 –name "CentOS_8" –description "Content view for CentOS 8"
 131 for i in $(seq 64 68); do hammer content-view add-repository –organization-id 1 –name "CentOS_8" –product "CentOS 8 Linux for x86_64" –repository-id "$i"; for i in $(seq 2 6); do hammer content-view add-repository –organization-id 1 –name "CentOS_8" –product "CentOS 8 Linux for x86_64" –repository-id "$i";
 132 for i in $(seq 2 6); do hammer content-view add-repository –organization-id 1 –name "CentOS_8" –product "CentOS 8 Linux for x86_64" –repository-id "$i"; for i in $(seq 2 6); do hammer content-view add-repository –organization-id 1 –name "CentOS_8" –product "CentOS 8 Linux for x86_64" –repository-id "$i"; done;
 133 for i in $(seq 2 6); do hammer content-view add-repository –organization-id 1 –name "CentOS_8" –product "CentOS 8 Linux for x86_64" –repository-id "$i"; done
 134 hammer content-view publish –organization-id 1 –name "CentOS_8" –description "Publishing repositories"
 135 hammer lifecycle-environment list –organization-id 1
 136 hammer activation-key create –organization-id 1 –name "centos8" –description "CentOS 8 Activation Key" –lifecycle-environment "Library" –content-view "CentOS_8" –unlimited-hosts
 137 Ahammer subscription list –organization-id 1
 138 hammer subscription list –organization-id 1
 139 hammer activation-key add-subscription –organization-id 1 –name "centos8" –quantity "1" –subscription-id 1
 140 subscription-manager identity
 141 rpm -Uvh http://foreman.internal-lab.net/pub/katello-ca-consumer-latest.noarch.rpm
 142 subscription-manager register –org="Lab" –activationkey="centos8"

137 hammer subscription list –organization-id 1
 138 hammer subscription list –organization-id 1
 139 hammer activation-key add-subscription –organization-id 1 –name "centos8" –quantity "1" –subscription-id 1
 140 subscription-manager identity
 141 rpm -Uvh http://foreman.internal-lab.net/pub/katello-ca-consumer-latest.noarch.rpm
 142 subscription-manager register –org="Lab" –activationkey="centos8"

----

## Monitoring

Link:
* https://community.theforeman.org/t/monitoring-foreman-with-prometheus/16466
* https://community.theforeman.org/t/monitoring-foreman-with-prometheus-via-statsd/21508

WARNING: statsd is prefered than prometheus

* Install package
----

yum install foreman-telemetry

----

* Enable prometheus in settings.yml
----

:telemetry:
 :prometheus:
 :enabled: true

----

Issues

* RAM
----

Insufficient memory for tuning size
Tuning profile 'default' requires at least 8 GB of memory and 1 CPU cores

----

* Package
----

Failed to ensure foreman-selinux, katello-selinux, candlepin-selinux, pulpcore-selinux are installed

----
https://community.theforeman.org/t/pulpcore-selinux-failed-to-install-in-new-installation/26631
----

yum install selinux-policy

----
https://docs.theforeman.org/3.0/Installing_Server_on_Red_Hat/index-katello.html#repositories-centos-8 not followed properly...
https://docs.theforeman.org/nightly/Quickstart_Guide/index-katello.html

* Centos 8 - Foreman 3.0 Katello 4.2
----

2022-05-16 21:23:20 [NOTICE] [configure] 1500 configuration steps out of 1725 steps complete.
2022-05-16 21:24:04 [ERROR ] [configure] Error making PUT request to Foreman at https://foreman.internal-lab.net/api/v2/instance_hosts/foreman.internal-lab.net: Response: 404 Not Found: The requested resource was not found in Foreman at foreman.internal-lab.net
2022-05-16 21:24:04 [ERROR ] [configure] /Stage[main]/Foreman::Register/Foreman_instance_host[foreman-foreman.internal-lab.net]/ensure: change from 'absent' to 'present' failed: Error making PUT request to Foreman at https://foreman.internal-lab.net/api/v2/instance_hosts/foreman.internal-lab.net: Response: 404 Not Found: The requested resource was not found in Foreman at foreman.internal-lab.net
2022-05-16 21:25:16 [ERROR ] [configure] Error making PUT request to Foreman at https://foreman.internal-lab.net/api/v2/smart_proxies/1/hosts/1: Response: 404 Not Found: The requested resource was not found in Foreman at foreman.internal-lab.net
2022-05-16 21:25:16 [ERROR ] [configure] /Stage[main]/Foreman_proxy::Register/Foreman_smartproxy_host[foreman-proxy-foreman.internal-lab.net]/ensure: change from 'absent' to 'present' failed: Error making PUT request to Foreman at https://foreman.internal-lab.net/api/v2/smart_proxies/1/hosts/1: Response: 404 Not Found: The requested resource was not found in Foreman at foreman.internal-lab.net
2022-05-16 21:26:52 [NOTICE] [configure] System configuration has finished.

There were errors detected during install.
 Please address the errors and re-run the installer to ensure the system is properly configured.
 Failing to do so is likely to result in broken functionality.

The full log is at /var/log/foreman-installer/katello.log

----

* Centos 8 - Night 4.5.0-0.5
----

2022-05-16 22:10:06 [NOTICE] [configure] Starting system configuration.
2022-05-16 22:11:16 [ERROR ] [configure] Execution of '/bin/dnf -d 0 -e 1 -y install katello' returned 1: Error:
2022-05-16 22:11:16 [ERROR ] [configure] Problem: package katello-4.5.0-0.1.master.el8.noarch requires rubygem-katello, but none of the providers can be installed