= FreeIPA

Tutorial followed: https://computingforgeeks.com/how-to-install-and-configure-freeipa-server-on-rhel-centos-8/

== Prerequisits

FreeIPA Server installation requirements
* Server with 4gb ram – I got failed installations for 1GB and 2GB RAM
* Fresh installation of RHEL / CentOS 8 server
* 2 vCPUs
* Port 443 and 80 not used by another application
* FQDN – Resolvable over the public or private DNS server
* 10 GB Disk space

== Installation

Bash commands

[source,bash]
----
sudo setenforce 0
sudo sed -i 's/^SELINUX=.*/SELINUX=permissive/g' /etc/selinux/config
yum -y install @idm:DL1
yum -y install freeipa-server
yum install ipa-server-dns bind-dyndb-ldap
echo "192.168.100.177 citools.internal-lab.net" >> /etc/hosts
export HNAME="citools.internal-lab.net"
hostnamectl set-hostname $HNAME --static
hostname $HNAME
sudo ipa-server-install --setup-dns
sudo firewall-cmd --add-service={http,https,dns,ntp,freeipa-ldap,freeipa-ldaps} --permanent
sudo firewall-cmd --reload
----

FreeIPA end config example:

----
The IPA Master Server will be configured with:
Hostname:       citools.internal-lab.net
IP address(es): 192.168.100.177
Domain name:    internal-lab.net
Realm name:     INTERNAL-LAB.NET

The CA will be configured with:
Subject DN:   CN=Certificate Authority,O=INTERNAL-LAB.NET
Subject base: O=INTERNAL-LAB.NET
Chaining:     self-signed

BIND DNS server will be configured to serve IPA domain with:
Forwarders:       No forwarders
Forward policy:   only
Reverse zone(s):  No reverse zone
----

== Free IPA Command

* 

Install ipa-client

[source,bash]
----
yum install ipa-client
----

* 

Start onboarding from clinet

----
ipa-client-install --domain=internal-lab.net --server=citools.internal-lab.net --realm=INTERNAL-LAB.NET
----

* Automating ipa-client-install command

* 

On IPA Server:

[source,bash]
----
ipa -v host-add test.internal-lab.net --password=secret --ip-address=1.1.1.1
----

____

An IP address is required but it does not need to resolv and it will be updated in real client onboarding: ipa: WARNING: The host was added but the DNS update failed with: All nameservers failed to answer the query for DNS reverse zone 1.1.1.1.in-addr.arpa.

____

* 

On Client Host

[source,bash]
----
ipa-client-install --domain=internal-lab.net --server=citools.internal-lab.net --realm=INTERNAL-LAB.NET --enable-dns-updates --mkhomedir -w secret --unattended
----

* 

Remove a host from freeipa server

[source,bash]
----
ipa host-del <hostname> --updatedns
----

== Kickstart onboarding

[source,bash]
----
ssh root@citools ipa host-add "$hostname" --password=secret --ip-address=1.1.1.1;
----

[source,bash]
----
sed -i "s#/usr/sbin/ipa-client-install --hostname=.*#/usr/sbin/ipa-client-install --hostname=$hostname --domain=internal-lab.net --enable-dns-updates --mkhomedir -w secret --realm=INTERNAL-LAB.NET --server=citools.internal-lab.net --unattended#g" /home/luc/Documents/lab/new/ks.cfg;
----

* Kickstart file: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/installing_identity_management/installing-an-ipa-client-with-kickstart_installing-identity-management#kickstart-file-for-client-installation_client-kickstart
```
%post –log=/root/ks-post.log

= Generate SSH keys; ipa-client-install uploads them to the IdM server by default

/usr/libexec/openssh/sshd-keygen rsa

= Run the client install script

/usr/sbin/ipa-client-install –hostname=test.internal-lab.net –domain=internal-lab.net –enable-dns-updates –mkhomedir -w secret –realm=INTERNAL-LAB.NET –server=citools.internal-lab.net –unattended

%end

----

## Additionnal

### Ubuntu DNS configuration

FreeIPA is also a DNS Server. Here is the configuration used on ubuntu to add freeipa DNS resolver

* Set a additional DNS server in Ubunutu: https://www.tecmint.com/set-permanent-dns-nameservers-in-ubuntu-debian/
----

sudo apt install resolvconf
systemctl status resolvconf.service
systemctl enable resolvconf.service

----

* Add your entries in: /etc/resolvconf/resolv.conf.d/head
----

nameserver 192.168.100.177

----

* Restart the service
----

systemctl restart resolvconf.service

----

## Issues enountered

* Module issue! Have to enable DL1 module to find ipa package
----

yum module info idm:DL1
yum -y install @idm:DL1

dnf module enable idm:DL1
```